# Generated by Django 5.0.6 on 2024-08-22 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='ngo_id',
            field=models.ForeignKey(db_column='n_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.ngo_details'),
            preserve_default=False,
        ),
    ]
